steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/prolog-pokedex:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/prolog-pokedex", "."]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "prolog-pokedex"
      - "--image"
      - "gcr.io/$PROJECT_ID/prolog-pokedex"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
images: ["gcr.io/$PROJECT_ID/prolog-pokedex"]
