steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/prolog-pokedex:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/prolog-pokedex",
        "--cache-from",
        gcr.io/$PROJECT_ID/prolog-pokedex",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/prolog-pokedex"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "prolog-pokedex"
      - "--image"
      - "gcr.io/$PROJECT_ID/prolog-pokedex:latest"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
images: ["gcr.io/$PROJECT_ID/prolog-pokedex"]
# NOTE: this has been configured to use a separate service account, so we must
# specify logging explicitly
options:
  logging: CLOUD_LOGGING_ONLY
